version: '3.9'

services:
  db:
    image: postgres:14.0-alpine
    container_name: pg-forum
    networks:
      - app-net
    environment:
      - POSTGRES_PASSWORD=1807
      - POSTGRES_USER=moura
      - POSTGRES_DB=dbForum
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5434:5432"
    volumes:
      - ./pg-data/pgforum:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "moura", "-d", "dbForum", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-net
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-net:
    driver: bridge